# Generated by Django 3.0.5 on 2021-02-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_reviews', '0002_auto_20210221_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
